### ISSUE TITLE
seeding from time will make everyone have different solar systems

### ISSUE THREAD

**Issue by KrzysztofWojnarowski** [jstasiaczek/space_station_game#1]
https://github.com/jstasiaczek/space_station_game/blob/d7d72b0cd37eb9acc857b54e0ae01edc85d4443b/src/scenes/SystemScene.ts#LL52C33-L52C33

Above you generate systems basing on timedate. You might want to consider seeding generator on initing the game and in line above use next() function of generator instead . This way everyone will have thesame set of randomly generated solar systems. Not mentioning that this will ease debuging and testing

**Comment by jstasiaczek** [comment]
This is done only for testing. Please consider that this is pre-alpha,
